membersrvc:
  # try 'docker ps' to see the container status after starting this compose
  container_name: membersrvc
  image: hyperledger/fabric-membersrvc
  expose:
    - "7054"
  ports:
    - "7054:7054"
  # environment:
  #   # check out what these mean!
  #   - MEMBERSRVC_CA_ACA_ENABLED=true
  #   - MEMBERSRVC_CA_TCA_ATTRIBUTE-ENCRYPTION_ENABLED=true
  volumes:
    - ./membersrvc.yaml:/opt/gopath/src/github.com/hyperledger/fabric/membersrvc/membersrvc.yaml
  command: membersrvc
  

vp:
  image: hyperledger/fabric-peer
  ports:
    - 7050:7050 # rest
    - 7051:7051 # grpc
    # - 7052:7052
    - 7053:7053
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    # - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_PEER_ID=vp
    - CORE_LOGGING_LEVEL=INFO
    # - CORE_SECURITY_ENROLLID=will
    # - CORE_SECURITY_ENROLLSECRET=pwd123
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - membersrvc
  command: peer node start --peer-chaincodedev













